version: "3.3"
services:
    ffbo.neurokernel_component:
        container_name: ffbo.neurokernel_component
        tty: true
        build:
            context: .
            dockerfile: ./Dockerfile
        image: fruitflybrain/ffbo.neurokernel_component:local
        networks:
            - ffbonet
networks:
    ffbonet:
        external: true
